import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "animate.css";
import "./globals.css";
import Footer from "@/components/footer/footer";
import Header from "@/components/header/header";
import "react-datepicker/dist/react-datepicker.css";
import { AuthProvider } from "@/services/AuthProvider"; // Import AuthProvider, điều chỉnh đường dẫn nếu cần
import ChatbotPopup from "@/components/chatbotAI/chatBotPopup";
import { LoadingProvider } from "@/contexts/LoadingContext";
import GlobalLoading from "@/components/loadingPage/GlobalLoading";
import CartProvider from "@/services/CartProvider";
import { ToastContainer } from "react-toastify";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <head>
        {/* _app.tsx hoặc layout.tsx */}
        <link rel="preload" as="image" href="/img/banner1.webp" />
        <link rel="preload" as="image" href="/img/logo-doc.png" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ToastContainer
          position="top-right"
          autoClose={3000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          pauseOnHover
          draggable
          theme="colored"
          style={{ zIndex: 9999 }}
        />
        <LoadingProvider>
          <AuthProvider>
            <CartProvider>
              <GlobalLoading />
              <Header />
              {children}
              <Footer />
            </CartProvider>
          </AuthProvider>
          <ChatbotPopup />
        </LoadingProvider>
      </body>
    </html>
  );
}
